name: reduction_bandits
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - ipython
  - jupyter
  - pandas
  - pip
  - pip:
    - cython==0.29.32
    - joblib==1.1.0
    - scikit-surprise==1.1.1
    - scipy==1.9.0
